// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfgyoehojtdvkfjmiabu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZ3lvZWhvanRkdmtmam1pYWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTE4NTgsImV4cCI6MjA3MjE4Nzg1OH0.vI_Tpq-5QNBAtqpxeVSK0_enrXy1HQ9y0Kw7_PhM6rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});